core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=!"C:/Users/user/Desktop/PortableGit/mingw64/libexec/git-core/git-credential-manager-core.exe"
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
user.name=samuelmuthembwa
user.email=70405740+samuelmuthembwa@users.noreply.github.com
credential.helperselector.selected=manager-core
http.version=HTTP/1.1
http.postbuffer=524288000
http.sslbackend=openssl
http.proxy=http://192.168.43.1:8080
core.compression=0
remote.origin.proxy=
remote.origin.proxy=https://26.26.26.1:8080
remote.origin.proxy=http://26.26.26.1:8080
remote.origin.proxy=https://192.168.43.1:8080
http.https://domain.com.sslverify=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.heroku.url=https://git.heroku.com/alita2121.git
remote.heroku.fetch=+refs/heads/*:refs/remotes/heroku/*
user.name=samuelmuthembwa
user.email=sammuthembwa926@gmail.com
remote.origin.url=https://github.com/samuelmuthembwa/alitabot.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
